In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline


df=pd.read_csv('agridata.csv')
df.head()

,commodity_name,state,district,market,min_price,max_price,modal_price,date
0,Ajwan,Gujarat,Amreli,Amreli,63.25,79.55,79.55,2019-05-22
1,Ajwan,Gujarat,Banaskanth,Dhanera,80.05,80.05,80.05,2019-05-22
2,Ajwan,Gujarat,Jamnagar,Jamnagar,90.00,155.00,122.50,2019-05-22
3,Ajwan,Gujarat,Mehsana,Kadi,94.50,112.50,107.00,2019-05-22
4,Ajwan,Gujarat,Mehsana,Unjha,21.25,148.50,99.75,2019-05-22

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 836977 entries, 0 to 836976
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   commodity_name  836976 non-null  object
 1   state           836977 non-null  object
 2   district        836977 non-null  object
 3   market          836977 non-null  object
 4   min_price       836976 non-null  float64
 5   max_price       836976 non-null  float64
 6   modal_price     836976 non-null  float64
 7   date            836976 non-null  object
dtypes: float64(3), object(5)
memory usage: 51.1+ MB

In [7]:
df.isnull().sum()

commodity_name    1
state             0
district          0
market            0
min_price         1
max_price         1
modal_price       1
date              1
dtype: int64

In [8]:
df.columns

Index(['commodity_name', 'state', 'district', 'market', 'min_price',
       'max_price', 'modal_price', 'date'],
      dtype='object')

In [9]:
data2=df.copy()

In [12]:
data2=data2.dropna()

In [13]:
data2.isnull().sum()

commodity_name    0
state             0
district          0
market            0
min_price         0
max_price         0
modal_price       0
date              0
dtype: int64

In [14]:
data2=data2.head(800000)

In [15]:
data2["date"][1]

'2019-05-22'

In [20]:
str=data2["date"][1]
str2=str.split('-')
print(str)
print(str2)
print(str2[1])

2019-05-22
['2019', '05', '22']
05

In [21]:
Dict={1:"January",2:"February",3:"March",4:"April",5:"May",6:"June",7:"July",8:"August",9:"September",10:"October",11:"November",12:"December"}
print(Dict)

{1: 'January', 2: 'February', 3: 'March', 4: 'April', 5: 'May', 6: 'June', 7: 'July', 8: 'August', 9: 'September', 10: 'October', 11: 'November', 12: 'December'}

In [22]:
Dict[1]

'January'

In [24]:
month_column=[]
for rr in data2["date"]:
    str=rr
    str2=str.split('-')
    month_column.append(Dict[int(str2[1])])

In [25]:
len(month_column)

800000

In [26]:
data2["month_column"]=month_column

In [27]:
data2["month_column"]

0          May
1          May
2          May
3          May
4          May
          ...
799995    July
799996    July
799997    July
799998    July
799999    July
Name: month_column, Length: 800000, dtype: object

In [28]:
data2["month_column"].unique()

array(['May', 'June', 'July', 'August', 'September', 'October',
       'November', 'December', 'March', 'April'], dtype=object)

In [29]:
season_names=[]

In [30]:
for tt in data2["month_column"]:
    if tt=="January" or tt=="February":
        season_names.append("winter")
    elif tt=="March" or tt=="April":
        season_names.append("spring")
    elif tt=="May" or tt=="June":
        season_names.append("summer")
    elif tt=="July" or tt=="August":
        season_names.append("monsoon")
    elif tt=="September" or tt=="October":
        season_names.append("autumn")
    elif tt=="November" or tt=="December":
        season_names.append("pre winter")

In [31]:
data2["season_names"]=season_names

In [32]:
data2.head()

,commodity_name,state,district,market,min_price,max_price,modal_price,date,month_column,season_names
0,Ajwan,Gujarat,Amreli,Amreli,63.25,79.55,79.55,2019-05-22,May,summer
1,Ajwan,Gujarat,Banaskanth,Dhanera,80.05,80.05,80.05,2019-05-22,May,summer
2,Ajwan,Gujarat,Jamnagar,Jamnagar,90.00,155.00,122.50,2019-05-22,May,summer
3,Ajwan,Gujarat,Mehsana,Kadi,94.50,112.50,107.00,2019-05-22,May,summer
4,Ajwan,Gujarat,Mehsana,Unjha,21.25,148.50,99.75,2019-05-22,May,summer